Repository skeleton-project-team-4/skeleton-project, pull requests merged in 2025-04, with the labels that each got.

#1 [FEAT] : 각 엔드포인트 별 store 추가
  db.json
  package.json
  src/stores/category.js
  src/stores/transactions.js
Labels: enhancement

#4 [FEAT] 달력, 월별 요약 구현
  db.json
  package-lock.json
  package.json
  src/components/MonthCalendar.vue
  src/components/MonthHistory.vue
  src/components/MonthSummary.vue
  src/main.js
Labels: enhancement

#5 [FEAT] : 거래내역 추가 및 상세 모달 창 추가
  src/components/TransactionModal.vue
  src/router/index.js
  src/stores/transactions.js
  src/views/NotFound.vue
Labels: enhancement

#13 [FIX] : 거래내역 조회 필터링 수정
  db.json
  src/stores/transactions.js
Labels: bug

#19 [FIX] : transactionstore 수정 및 NotFound 페이지 추가구현
  src/stores/transactions.js
  src/views/NotFound.vue
Labels: bug, enhancement

#22 [FIX] : 거래내역 수정 시 금액에서 발생하는 버그 해결
  src/components/TransactionModal.vue
Labels: enhancement
